version: 1.2
workflows:
  - name: IsoQuantMakeDB
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantMakeDB.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: IsoQuantQuantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantQuantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LIQAQuantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LIQA/liqaQuantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: pacbioRnaseqcFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/rnaseqc/pacbioRnaseqcFromBAM.wdl
  - name: pacbioRnaseqcPlusFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/rnaseqc/pacbioRnaseqcPlusFromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: Sqanti3FromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/sqanti3/sqanti3FromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: StringTieMerge
    subclass: WDL
    primaryDescriptorPath: /LR-tools/stringtie_merge/stringtie_merge_and_reestimate.wdl
    authors:
      - orcid: 0000-0002-2603-1660
