version: 1.2
workflows:
  - name: IsoQuant-makeDB
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantQuantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: IsoQuant-quantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/IsoQuant/IsoQuantMakeDB.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: LIQA-quantify
    subclass: WDL
    primaryDescriptorPath: /LR-tools/LIQA/liqa_quantify.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: pacbioRnaseqcFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/rnaseqc/pacbioRnaseqcFromBAM.wdl
  - name: pacbioRnaseqcPlusFromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/rnaseqc/pacbioRnaseqcPlusFromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: Sqanti3FromBAM
    subclass: WDL
    primaryDescriptorPath: /LR-tools/sqanti3/sqanti3FromBAM.wdl
    authors:
      - orcid: 0000-0002-2603-1660
  - name: StringTie-merge
    subclass: WDL
    primaryDescriptorPath: /LR-tools/stringtie_merge/stringtie_merge_and_reestimate.wdl
    authors:
      - orcid: 0000-0002-2603-1660
